### ISSUE TITLE
How to add static IP addressing on nodes ?

### ISSUE THREAD

**Issue by rguyennot** [frank-at-suse/vsphere_rancher_cluster#2]
Hi @frank-at-suse 👋

First, thank you for your amazing work 🙏
Could you please explain us how to get static IPv4 addressing on clusters nodes deployed with Terraform ? 

Regards

**Comment by frank-at-suse** [comment]
Thanks for the feedback!  [A Static IP example has been added to the README.md](https://github.com/frank-at-suse/vsphere_rancher_cluster#static-ip-addressing) has been added.
